server:
  port: 9999
  servlet:
    context-path: /blog

#公共配置与profiles选择无关
mybatis:
  type-aliases-package: pers.skeaven.blog.bean.po
  mapper-locations: classpath:mapper/*.xml

#开发配置
spring:
  resources:
    static-locations: classpath:static/,file:static/
  datasource:
    url: jdbc:mysql://192.168.137.129:3306/blog?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: my-secret-pw
    driver-class-name: com.mysql.cj.jdbc.Driver


#项目配置
project-path:
  markdown-path: /static/markdown